=== afrankenthal/Chewie/xml/ChewieConfiguration.dtd
<?xml encoding="ISO-8859-1"?>
<!ELEMENT ChewieConfiguration(General*)(Converter*)(Scan*)>
 <!ELEMENT Converter>
  <!ATTLIST Converter MaxEvents CDATA #REQUIRED>
  <!ATTLIST Converter Threads   CDATA #REQUIRED>
  <!ATTLIST Converter IsToLimit CDATA #REQUIRED>
 <!ELEMENT General(Analysis* Plane*)>
  <!ATTLIST General PreAnalysisMaxEvents CDATA #REQUIRED>
  <!ATTLIST General AnalysesMaxEvents CDATA #REQUIRED>
  <!ATTLIST General Threads CDATA #REQUIRED>
  <!ELEMENT Plane(Window+)(Calibrations*)>
   <!ATTLIST Plane Name CDATA #REQUIRED>
   <!ATTLIST Plane XRocs CDATA #REQUIRED>
   <!ATTLIST Plane YRocs CDATA #REQUIRED>
   <!ATTLIST Plane XPitch CDATA #REQUIRED>
   <!ATTLIST Plane YPitch CDATA #REQUIRED>
   <!ATTLIST Plane ZPosition CDATA #REQUIRED> 
   <!ATTLIST Plane ZRotation CDATA #REQUIRED>  
    <!ELEMENT Window(LowerCol+ HigherCol+ LowerRow+ HigherRow+ RemovedPixel*)>
     <!ELEMENT LowerCol (#PCDATA)+>
     <!ELEMENT HigherCol (#PCDATA)+>
     <!ELEMENT LowerRow (#PCDATA)+>
     <!ELEMENT HigherRow (#PCDATA)+>
     <!ELEMENT RemovedPixel (#PCDATA)*>
      <!ATTLIST RemovedPixel Row CDATA #REQUIRED>
      <!ATTLIST RemovedPixel Col CDATA #REQUIRED>
    <!ELEMENT Calibrations (File+)>
     <!ATTLIST Use CDATA #REQUIRED>
     <!ELEMENT File (#PCDATA)+>   
 <!ELEMENT Analysis(MinHits+)(CellCharge*)(TotalCharge*)(cut*)(calibCut*)(BadPlanesHits*)>
  <!ATTLIST Analysis Type CDATA #REQUIRED>
  <!ATTLIST Analysis IsToRun CDATA #REQUIRED>
  <!ATTLIST Analysis StandardCut CDATA #REQUIRED>
  <!ATTLIST Analysis Priority CDATA #REQUIRED>
  <!ELEMENT MinHits(#PCDATA)+>
  <!ELEMENT BadPlanesHits(#PCDATA)+>
  <!--ELEMENT priority(#PCDATA)+-->
  <!ELEMENT CellCharge(threashold+ maxCharge+)>
   <!ELEMENT Threashold(#PCDATA)+>
   <!ELEMENT MaxCharge(#PCDATA)+>
  <!ELEMENT TotalCharge(minTotCharge+ maxTotCharge+)>
   <!ELEMENT MinTotCharge(#PCDATA)+>
   <!ELEMENT MaxTotCharge(#PCDATA)+>
  <!ELEMENT Cut (#PCDATA)*>
   <!ATTLIST Cut CutType CDATA #REQUIRED>
   <!ATTLIST Cut CutString CDATA #REQUIRED> 
  <!ELEMENT CalibCut(par+)>
   <!ELEMENT Par(min+ max+)>
    <!ATTLIST ParID CDATA #REQUIRED>
 <!ELEMENT Scan (file*)>
  <!ELEMENT File (#PCDATA)*>
   <!ATTLIST File value CDATA #REQUIRED>
   <!ATTLIST File name CDATA #REQUIRED>

=== afrankenthal/Chewie/xml/2017November_ChewieConfiguration_Americans_Andre.xml
<?xml version='1.0' encoding='iso-8859-1'?>
<!DOCTYPE ChewieConfiguration SYSTEM './ChewieConfiguration.dtd'>
<ChewieConfiguration>
  <Converter Threads="4" IsToLimit="no" MaxEvents="9999"/>
  <General AnalysesMaxEvents="1000" Threads="4" IsToLimit="no" MaxEvents="5" PreAnalysisMaxEvents="400000">
    <Plane Calibration="N.A." Name="Station: 5 - Plaq: 0" YRocs="1" Id="Strip_Telescope_Upstream0" XRocs="1" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>639</HigherCol>
        <LowerRow>0</LowerRow>
        <HigherRow>0</HigherRow>
      </Window>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 5 - Plaq: 1" YRocs="1" Id="Strip_Telescope_Upstream1" XRocs="1" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>639</HigherCol>
        <LowerRow>0</LowerRow>
        <HigherRow>0</HigherRow>
      </Window>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 5 - Plaq: 2" YRocs="1" Id="Strip_Telescope_Upstream2" XRocs="1" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>639</HigherCol>
        <LowerRow>0</LowerRow>
        <HigherRow>0</HigherRow>
      </Window>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 5 - Plaq: 3" YRocs="1" Id="Strip_Telescope_Upstream3" XRocs="1" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>639</HigherCol>
        <LowerRow>0</LowerRow>
        <HigherRow>0</HigherRow>
      </Window>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 6 - Plaq: 0" YRocs="1" Id="Strip_Telescope_Upstream4" XRocs="1" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>639</HigherCol>
        <LowerRow>0</LowerRow>
        <HigherRow>0</HigherRow>
      </Window>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 6 - Plaq: 1" YRocs="1" Id="Strip_Telescope_Upstream5" XRocs="1" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>639</HigherCol>
        <LowerRow>0</LowerRow>
        <HigherRow>0</HigherRow>
      </Window>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 6 - Plaq: 2" YRocs="1" Id="Strip_Telescope_Upstream6" XRocs="1" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>639</HigherCol>
        <LowerRow>0</LowerRow>
        <HigherRow>0</HigherRow>
      </Window>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 6 - Plaq: 3" YRocs="1" Id="Strip_Telescope_Upstream7" XRocs="1" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>639</HigherCol>
        <LowerRow>0</LowerRow>
        <HigherRow>0</HigherRow>
      </Window>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 2 - Plaq: 0" YRocs="2" Id="Telescope_Upstream0" XRocs="3" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>155</HigherCol>
        <LowerRow>0</LowerRow>
        <HigherRow>159</HigherRow>
      </Window>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 2 - Plaq: 1" YRocs="3" Id="Telescope_Upstream1" XRocs="3" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>155</HigherCol>
        <LowerRow>0</LowerRow>
        <HigherRow>159</HigherRow>
      </Window>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 2 - Plaq: 2" YRocs="2" Id="Telescope_Upstream2" XRocs="4" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>207</HigherCol>
        <LowerRow>0</LowerRow>
        <HigherRow>159</HigherRow>
      </Window>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 2 - Plaq: 3" YRocs="2" Id="Telescope_Upstream3" XRocs="4" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>207</HigherCol>
        <LowerRow>0</LowerRow>
        <HigherRow>159</HigherRow>
      </Window>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 0 - Plaq: 0" YRocs="2" Id="Telescope_Downstream0" XRocs="4" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>207</HigherCol>
        <LowerRow>0</LowerRow>
        <HigherRow>159</HigherRow>
      </Window>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 0 - Plaq: 1" YRocs="2" Id="Telescope_Downstream1" XRocs="4" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>207</HigherCol>
        <LowerRow>0</LowerRow>
        <HigherRow>159</HigherRow>
      </Window>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 0 - Plaq: 2" YRocs="2" Id="Telescope_Downstream2" XRocs="3" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>155</HigherCol>
        <LowerRow>0</LowerRow>
        <HigherRow>159</HigherRow>
      </Window>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 0 - Plaq: 3" YRocs="2" Id="Telescope_Downstream3" XRocs="3" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>155</HigherCol>
        <LowerRow>0</LowerRow>
        <HigherRow>159</HigherRow>
      </Window>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 7 - Plaq: 0" YRocs="1" Id="Strip_Telescope_Downstream0" XRocs="1" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>639</HigherCol>
        <LowerRow>0</LowerRow>
        <HigherRow>0</HigherRow>
      </Window>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 7 - Plaq: 1" YRocs="1" Id="Strip_Telescope_Downstream1" XRocs="1" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>639</HigherCol>
        <LowerRow>0</LowerRow>
        <HigherRow>0</HigherRow>
      </Window>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 7 - Plaq: 2" YRocs="1" Id="Strip_Telescope_Downstream2" XRocs="1" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>639</HigherCol>
        <LowerRow>0</LowerRow>
        <HigherRow>0</HigherRow>
      </Window>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 7 - Plaq: 3" YRocs="1" Id="Strip_Telescope_Downstream3" XRocs="1" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>639</HigherCol>
        <LowerRow>0</LowerRow>
        <HigherRow>0</HigherRow>
      </Window>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 7 - Plaq: 4" YRocs="1" Id="Strip_Telescope_Downstream4" XRocs="1" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>639</HigherCol>
        <LowerRow>0</LowerRow>
        <HigherRow>0</HigherRow>
      </Window>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 7 - Plaq: 5" YRocs="1" Id="Strip_Telescope_Downstream5" XRocs="1" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>639</HigherCol>
        <LowerRow>0</LowerRow>
        <HigherRow>0</HigherRow>
      </Window>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 4 - Plaq: 0" YRocs="1" Id="Dut0" ZPosition="6" XRocs="1" ZRotation="90" YPitch="100" XPitch="25">
      <Window>
        <LowerCol>1</LowerCol>
        <HigherCol>311</HigherCol>
        <LowerRow>1</LowerRow>
        <HigherRow>79</HigherRow>
      </Window>
      <Calibrations Use="no">
        <File>/path_to_calibration/file_name.root</File>
      </Calibrations>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 4 - Plaq: 1" YRocs="1" Id="Dut1" ZPosition="5" XRocs="1" ZRotation="90" YPitch="50" XPitch="50">
      <Window>
        <LowerCol>1</LowerCol>
        <HigherCol>155</HigherCol>
        <LowerRow>1</LowerRow>
        <HigherRow>159</HigherRow>
      </Window>
      <Calibrations Use="no">
        <File>/path_to_calibration/file_name.root</File>
      </Calibrations>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 4 - Plaq: 2" YRocs="1" Id="Dut2" ZPosition="-5" XRocs="1" ZRotation="90" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>1</LowerCol>
        <HigherCol>50</HigherCol>
        <LowerRow>1</LowerRow>
        <HigherRow>78</HigherRow>
      </Window>
      <Calibrations Use="no">
        <File>/path_to_calibration/file_name.root</File>
      </Calibrations>
    </Plane>
    <Plane Calibration="N.A." Name="Station: 4 - Plaq: 3" YRocs="1" Id="Dut3" ZPosition="-5" XRocs="1" ZRotation="90" YPitch="100" XPitch="150">
      <Window>
        <LowerCol>0</LowerCol>
        <HigherCol>51</HigherCol>
        <LowerRow>1</LowerRow>
        <HigherRow>78</HigherRow>
      </Window>
      <Calibrations Use="no">
        <File>/path_to_calibration/file_name.root</File>
      </Calibrations>
    </Plane>
    <Analysis Priority="0" IsToRun="yes" Type="Windows"/>
    <Analysis Priority="4" DoFits="no" StandardCut="yes" IsToRun="no" Type="Tracks">
      <MinHits>8</MinHits>
    </Analysis>
    <Analysis Priority="5" DoFits="no" StandardCut="yes" IsToRun="no" Type="TracksAfter">
      <MinHits>8</MinHits>
    </Analysis>
    <Analysis Priority="1" Module="Americans" DoFits="no" StandardCut="yes" IsToRun="yes" Type="Efficiency">
      <Cut CutString="numberOfTracks &lt;= 1 &amp;&amp; chi2/ndof &lt;= 5" CutType="main cut"/>
      <Cut CutString="" CutType="cell efficiency"/>
      <Cut CutString="yPixelResidualLocal[22] &lt;= 30 &amp;&amp; yPixelResidualLocal[22] >= -30 &amp;&amp; ySigmaIntercept &lt;= 8" CutType="cell efficiency X"/>
      <Cut CutString="xPixelResidualLocal[22] &lt;= 55 &amp;&amp; xPixelResidualLocal[22] >= -55 &amp;&amp; xSigmaIntercept &lt;= 8" CutType="cell efficiency Y"/>
      <MinHits>8</MinHits>
    </Analysis>
    <Analysis Priority="2" Module="Americans" DoFits="no" StandardCut="yes" IsToRun="yes" Type="Charge">
      <PixelMinimumCharge>0</PixelMinimumCharge>
      <PixelMaximumCharge>70000</PixelMaximumCharge>
